const movies = [
    {
        id: 0,
        name: "3:10 To Lillehammer",
        imgSrc: "./images/movieposters/3-10-to-lillehammer.jpg",
        price: 10.00,
        director: "John Doe",
        year: 2021,
        description: "Short about the movie. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        numberOfUnits: 1,
    }, 
    {
        id: 1,
        name: "Bad Moon Rising",
        imgSrc: "./images/movieposters/bad-moon-rising.jpg",
        price: 10.00,
        director: "John Doe",
        year: 2021,
        description: "Short about the movie. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        numberOfUnits: 1,
    },
    {
        id: 2,
        name: "Danger Zone",
        imgSrc: "./images/movieposters/danger-zone.jpg",
        price: 10.00,
        director: "John Doe",
        year: 2021,
        description: "Short about the movie. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        numberOfUnits: 1,
    },
    {
        id: 3,
        name: "The Last man",
        imgSrc: "./images/movieposters/the-last-man.jpg",
        price: 10.00,
        director: "John Doe",
        year: 2021,
        description: "Short about the movie. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        numberOfUnits: 1,
    },
    {
        id: 4,
        name: "Invasion",
        imgSrc: "./images/movieposters/invasion.jpg",
        price: 10.00,
        director: "John Doe",
        year: 2021,
        description: "Short about the movie. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        numberOfUnits: 1,
    },
];